### ISSUE TITLE
Release aarch64 

### ISSUE THREAD

**Issue by makayabou** [casimir/frigoligo#258]
Hello,

Frigolio seems wonderful, but i was trying to install it on my PineTab2, running on ARM Cortex-A55 with arch linux.
Would it be a lot of work for you guys to also release for aarch64 ?

Thanks

**Comment by casimir** [comment]
This is planned, hopefully for the (next) version 2.0 as it should be possible since the merge of #233.

The tricky part is to get a working build environment setup on ARM. I saw some news about GitHub Actions providing containers running on this architecture starting this month, this is promising. 

NB: This release is also a prerequisite for a flathub release https://github.com/flathub/flathub/pull/5247#discussion_r1603218805

**Comment by casimir** [comment]
@makayabou could you check if this build is working for you please? https://github.com/casimir/frigoligo/actions/runs/11766823647
